### ISSUE TITLE
<title><![CDATA[Black Nike Shirt]]></title>

### ISSUE THREAD

**Issue by lokutus24** [GreenCape/xml-converter#1]
Hello,

How can i use your repo with CDATA option?
<title><![CDATA[Black Nike Shirt]]></title>

Regards,
Gabor

**Comment by nibra** [comment]
Fixed in master. Thank you, @lokutus24, for your feedback!

**Comment by lokutus24** [comment]
Thank you! How can i add CDATA attribute to elements :)?

**Comment by nibra** [comment]
You can't. CDATA is just an alternative to escaping content.
```xml
<node><![CDATA[<&>]]</node>
```
is the same as
```xml
<node>&lt;&amp;&gt;</node>
```
which is what gets generated.

**Comment by lokutus24** [comment]
Thank you!
